### ISSUE TITLE
Question about the inductive performance of the model in 'Demo.m' file

### ISSUE THREAD

**Issue by panlinchao** [Gu-X/Semi-Supervised-Fuzzily-Weighted-Adaptive-Boosting-for-Classification#1]
Hi,
I truly appreciate the outstanding work you've done with SSFWAdaBoost. It has been a valuable resource for exploring semi-supervised learning models. Upon reviewing the 'Demo.m' file, I noticed that it primarily focuses on demonstrating transductive performance, where the unlabeled data also served as the test data. I was wondering if it might be possible for you to share the training procedure for the SSFWAdaBoost model or perhaps provide a demo for inductive testing? This additional information would greatly enhance our understanding and application of the model.
Thank you very much for considering my request. I look forward to any guidance you can provide.
Best regards!

**Comment by Gu-X** [comment]
A new demo is added for inductive setting.
